### ISSUE TITLE
To run sailor

### ISSUE THREAD

**Issue by YangpingLi** [YeoLab/sailor#4]
Hi,

I'm trying to run sailor on our HPC as a user. I first installed singularity via conda by "**conda install -c conda-forge singularity**". 
And I can see "singularity version 3.6.4" by run "**singularity --version**" to make sure singularity is installed.

Then I download the executable sailor "https://s3-us-west-1.amazonaws.com/sailor-1.0.4/sailor-1.0.4" to an empty folder and ran "**chmod +x sailor-1.0.4**" as described in the tutorial.

However, when I run **./sailor-1.0.4**, a weird error massage shows up:
**FATAL:   while extracting ./sailor-1.0.4: not a squashfs root filesystem**
Do you have any suggestion about this problem?

Thanks for advance!

**Comment by byee4** [comment]
Hi, it seems like an issue with trying to run singularity unprivilaged: https://github.com/hpcng/singularity/issues/3940

Is it possible to ask your HPC admins to install singularity and see if that helps you run the image?
